I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 60, in script
    
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 60, in script
    
  File "C:\Users\emila\Downloads\renpy-7.2.2-sdk\renpy\ast.py", line 664, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\emila\Downloads\renpy-7.2.2-sdk\renpy\ast.py", line 564, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'm' is not defined.

Windows-8-6.2.9200
Ren'Py 7.2.2.491
situationstrd svenska 1.0
Wed May 01 11:17:02 2019
